image: gitpod/workspace-postgres
tasks:
 - name: backend
   init: npm i -g @nestjs/cli --silent && cd backend && npm install --silent
   command: cd backend && npm start
 - name: frontend
   init: cd frontend && npm install --silent
   command: cd frontend && npm start

ports:
 - port: 5432
   onOpen: ignore
 - port: 5000
   onOpen: ignore
   visibility: public
 - port: 3000
   onOpen: open-preview
   visibility: public

vscode:
  extensions:
    - mtxr.sqltools-driver-pg
