image: gitpod/workspace-postgres
tasks:
 - name: Initialize backend
   init: npm i -g @nestjs/cli --silent && cd backend && npm install --silent
   command: npm start
 - name: Initialize frontend
   init: cd frontend && npm install --silent
   command: npm start

ports:
 - port: 5432
   onOpen: ignore
 - port: 5000
   onOpen: ignore
 - port: 3000
   onOpen: ignore

vscode:
  extensions:
    - mtxr.sqltools-driver-pg
