version: '3'
services:
  db:
    image: 'postgres:latest'
    container_name: postgres_db
    ports:
      - 54320:5432
    environment:
      POSTGRES_USER: gitpod
      POSTGRES_PASSWORD: gitpod
      POSTGRES_DB: postgres

  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: "Dockerfile"
    ports:
      - 5001:5000
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: "Dockerfile"
    ports:
      - 3000:80
    depends_on:
      - backend
