version: '3'
services:
  db:
    image: 'postgres:11'
    container_name: postgres_db
    network_mode: host
    ports:
      - "54320:5432"
    expose:
      - "54320"
    environment:
      POSTGRES_USER: gitpod
      POSTGRES_PASSWORD: gitpod
      POSTGRES_DB: postgres

  backend:
    container_name: backend
    network_mode: host
    build:
      context: backend
      dockerfile: "Dockerfile"
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      - WAIT_SLEEP_INTERVAL=30

  frontend:
    container_name: frontend
    network_mode: host
    build:
      context: frontend
      dockerfile: "Dockerfile"
    ports:
      - "3000:80"
    depends_on:
      - backend
